#!/bin/bash
# Copyright (C) 2018 by Adam Taylor
#
# This script fixes up the output from the README.org export to md that has problems with
# tables that have multi-line text (from pp-to-string output of customized variables)
#   - Replaces ":br-goes-here:" and subsequent spaces to "<br>&nbsp;" - the number of &nbsp; matches the number of spaces 
#   - Gets rid of the added <> around the http:// and https:// strings in the tables. Can't figure out an easy way to get
#     rid of them any other way.

#
old_readme_size=0
while [ $old_readme_size -ne $(stat -c%s README.md) ]; do
    old_readme_size=$(stat -c%s README.md)
    sed -i -e 's/\(:br-goes-here: *\) /\1\&nbsp;/g' README.md
done
sed -i -e 's/"<\(https*[^>]*\)>"/"\1"/g' -e 's/:br-goes-here:/<br>/g' README.md

