#!/bin/bash
# Copyright (C) 2018 by Adam Taylor
#
# This script fixes up the output from the README.org export to md that has problems with
# tables that have multi-line text (from pp-to-string output of customized variables)
#   - Gets rid of the added <> around the http:// and https:// strings in the tables. Can't figure out an easy way to get
#   - Replaces ":br-goes-here:" and subsequent spaces to "<br>&nbsp;" - the number of &nbsp; matches the number of spaces 
#   - Make any \n => <br>
#   For <td>.*</td> only:
#     - Get rid of the <sub>.*</sub> mistakenly added to code segments
#     - Get rid of <span class="underline">.* mistakenly added to code segments

old_readme_size=0
while [ $old_readme_size -ne $(stat -c%s README.md) ]; do
    old_readme_size=$(stat -c%s README.md)
    sed -i \
        -e 's/\(:br-goes-here: *\) /\1\&nbsp;/g' \
        -e 's/^\(<td.*\)<span class="underline">\(.*<\/td>\)$/\1\2/g' \
        -e 's/^\(<td.*\)<\/span>\(.*<\/td>\)$/\1\2/g' \
        -e 's/^\(<td.*\)<sub>\(.*<\/td>\)$/\1\2/g' \
        -e 's/^\(<td.*\)<\sub>\(.*<\/td>\)$/\1\2/g' \
        README.md

done
sed -i -e 's/"<\(https*[^>]*\)>"/"\1"/g' -e 's/:br-goes-here:/<br>/g' -e 's/\\n/<br>/g' README.md

